/**
 * Default school data bundled with the app (76 sites).
 * Edit this file directly, or use Add/Edit/Import CSV in the dashboard.
 * Updated: 2026-08-05
 */
const SEED_SCHOOLS = [
  {
    "id": 1,
    "ss": "JLB",
    "name": "Digital Evaluation Copies Edulearn",
    "link": "eval.edulearntechnologies.com",
    "status": "Undeployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 2,
    "ss": "JLB",
    "name": "Demo Site",
    "link": "demo.edulearntechnologies.com",
    "status": "In Progress",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 3,
    "ss": "JLB",
    "name": "EduLearn Academy",
    "link": "ea.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 4,
    "ss": "JLB",
    "name": "Savvy Tech",
    "link": "savvytech.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 5,
    "ss": "OMA",
    "name": "St. Mary's University",
    "link": "smu.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 6,
    "ss": "JGC",
    "name": "Maryknoll School of Lupon, Inc.",
    "link": "msl.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 7,
    "ss": "JGC",
    "name": "Philippine Women's College of Davao",
    "link": "pwc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 8,
    "ss": "VAC",
    "name": "Notre Dame of Banga Inc.",
    "link": "ndb.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 9,
    "ss": "VAC",
    "name": "Notre Dame of Dadiangas University - IBED Lagao",
    "link": "nddu.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 10,
    "ss": "VAC",
    "name": "Notre Dame of Marbel University - IBED",
    "link": "ndmu.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 11,
    "ss": "VAC",
    "name": "Notre Dame of Tacurong College Inc.",
    "link": "ndtc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 12,
    "ss": "VAC",
    "name": "St. Lorenzo School of Polomolok Inc.",
    "link": "slsp.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 13,
    "ss": "VAC",
    "name": "The Quantum Academy Inc.",
    "link": "tqa.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 14,
    "ss": "JBT",
    "name": "St. Rita's College of Balingasag Inc.",
    "link": "srcb.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 15,
    "ss": "JBT",
    "name": "Our Lady of Lourdes Elementary School, Inc.",
    "link": "olles.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 16,
    "ss": "JBT",
    "name": "Loyola School of Don Carlos",
    "link": "lsdc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 17,
    "ss": "JBT",
    "name": "Pilar High School, Inc.",
    "link": "phs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 18,
    "ss": "MLS",
    "name": "Holy Trinity University - Puerto Princesa",
    "link": "htu.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 19,
    "ss": "APG",
    "name": "Saint Peter's College of Ormoc",
    "link": "spco.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 20,
    "ss": "APG",
    "name": "Saint Thomas Aquinas College",
    "link": "stac.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 21,
    "ss": "APG",
    "name": "Saint Teresa School of Hilongos",
    "link": "stsh.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 22,
    "ss": "APG",
    "name": "Holy Trinity College Alangalang",
    "link": "htc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 23,
    "ss": "SLUZ",
    "name": "The Lady Mediatrix Institute, Inc.",
    "link": "tlmi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 24,
    "ss": "TMA",
    "name": "Nissi Academy, Inc.",
    "link": "na.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 25,
    "ss": "TMA",
    "name": "Paref Springdale School",
    "link": "pss.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 26,
    "ss": "TMA",
    "name": "Rosemont Hills Montessori College",
    "link": "rhmc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 27,
    "ss": "TMA",
    "name": "Sacred Heart School-Ateneo de Cebu",
    "link": "shs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 28,
    "ss": "TMA",
    "name": "San Carlos School of Cebu, Inc.",
    "link": "scsc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 29,
    "ss": "TMM",
    "name": "Immaculate Heart of Mary Academy",
    "link": "ihma.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 30,
    "ss": "TMM",
    "name": "Intellectual Development for Early Age School, Inc.",
    "link": "ideas.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 31,
    "ss": "TMM",
    "name": "Rainbow Connection Child Learning Center",
    "link": "rcclc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 32,
    "ss": "TMM",
    "name": "St. Scholastica's Academy of Tabunok",
    "link": "ssat.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 33,
    "ss": "TMM",
    "name": "Patronage of Mary Development School of Boljoon",
    "link": "pmds.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 34,
    "ss": "TMM",
    "name": "University of San Jose - Recoletos",
    "link": "usjr.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 35,
    "ss": "PVM",
    "name": "HOLY SPIRIT SCHOOL OF TAGBILARAN",
    "link": "hsst.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 36,
    "ss": "PVM",
    "name": "HOLY NAME UNIVERSITY",
    "link": "hnu.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 37,
    "ss": "PVM",
    "name": "BOHOL WISDOM SCHOOL",
    "link": "bws.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 38,
    "ss": "PVM",
    "name": "ST. LOUIS SCHOOL OF DON BOSCO",
    "link": "slsdb.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 39,
    "ss": "PVM",
    "name": "COLEGIO DE SANTA CATALINA DE ALEJANDRIA",
    "link": "cosca.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 40,
    "ss": "PVM",
    "name": "ST. AUGUSTINE ACADEMY OF BAYAWAN, INC.",
    "link": "saabi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 41,
    "ss": "PVM",
    "name": "SILLIMAN UNIVERSITY",
    "link": "su.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 42,
    "ss": "PVM",
    "name": "ST. NICHOLAS ACADEMY",
    "link": "sna.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 43,
    "ss": "PVM",
    "name": "UNIVERSITY OF BOHOL VICTORIANO D. TIROL ADVANCED LEARNING CENTER",
    "link": "ubvtdalc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 44,
    "ss": "SLUZ",
    "name": "ATENEO DE NAGA UNIVERSITY - GS",
    "link": "adnu.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 45,
    "ss": "OMA",
    "name": "Lord of Zion Divine School Inc.",
    "link": "lzds.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 46,
    "ss": "OMA",
    "name": "University of St. Louis Tuguegarao",
    "link": "uslt.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 47,
    "ss": "HPS",
    "name": "Aklan Catholic College",
    "link": "acc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 48,
    "ss": "HPS",
    "name": "Aklan Valley High School",
    "link": "avhs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 49,
    "ss": "HPS",
    "name": "Colegio de la Purisima Concepcion",
    "link": "cpc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 50,
    "ss": "HPS",
    "name": "Dao Catholic High School",
    "link": "dchs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 51,
    "ss": "HPS",
    "name": "Pandan Bay Institute",
    "link": "pbi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 52,
    "ss": "HPS",
    "name": "St. Augustine Academy of Patnongon",
    "link": "saapi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 53,
    "ss": "HPS",
    "name": "St. Anthony's College",
    "link": "sac.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 54,
    "ss": "HPS",
    "name": "St. Anthony's High School of Barbaza",
    "link": "sahsbi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 55,
    "ss": "HPS",
    "name": "St. Blaise High School",
    "link": "sbhs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 56,
    "ss": "HPS",
    "name": "St. Michael High School",
    "link": "smhs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 57,
    "ss": "HPS",
    "name": "St. Therese's High School",
    "link": "sths.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 58,
    "ss": "HPS",
    "name": "St. Vincent High School",
    "link": "svhs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 59,
    "ss": "HPS",
    "name": "Nuestra Señora del Pilar Parochial School",
    "link": "nsdpps.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 60,
    "ss": "HPS",
    "name": "Our Lady of Snow Institute",
    "link": "olsi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 61,
    "ss": "HPS",
    "name": "Parish School of St. Isidore",
    "link": "pssi.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 62,
    "ss": "HPS",
    "name": "San Sebastian Parochial School",
    "link": "ssps.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 63,
    "ss": "HPS",
    "name": "St. Catherine Academy",
    "link": "sca.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 64,
    "ss": "HPS",
    "name": "St. Lawrence Parochial School",
    "link": "slps.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 65,
    "ss": "HPS",
    "name": "Our Lady of Fatima Academy of Dao",
    "link": "olfa.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 66,
    "ss": "HPS",
    "name": "St. Joseph Academy of Bugasong",
    "link": "sjab.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 67,
    "ss": "HPS",
    "name": "St. Martin Academy of Dumalag",
    "link": "smad.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 68,
    "ss": "OMA",
    "name": "University of Baguio",
    "link": "ub.edulearntechnologies.com",
    "programs": "Elementary, Regular High School, Science High School",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 69,
    "ss": "OMA",
    "name": "Saint Catherine's School",
    "link": "scs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 70,
    "ss": "OMA",
    "name": "Saint Louis College",
    "link": "slc.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 71,
    "ss": "OMA",
    "name": "Saint Vincent School",
    "link": "svs.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 72,
    "ss": "PVM",
    "name": "Holy Family of Nazareth School of Tubigon, Inc.",
    "link": "hfns.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 73,
    "ss": "SLUZ BICOL",
    "name": "St. Agnes Academy, Inc.",
    "link": "saa.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 74,
    "ss": "APG",
    "name": "Liceo del Verbo Divino",
    "link": "lvd.edulearntechnologies.com",
    "status": "Deployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 75,
    "ss": "OMA",
    "name": "Lorma Colleges, Inc.",
    "link": "lci.edulearntechnologies.com",
    "status": "Undeployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  },
  {
    "id": 76,
    "ss": "OMA",
    "name": "BHC Educational Ins.",
    "link": "bhc.edulearntechnologies.com",
    "status": "Undeployed",
    "accountCreation": false,
    "teachers": false,
    "students": false,
    "enrollment": false
  }
];
